title: Maintain (holding page)
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Holding Page for Maintain
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maintain.community"
twitter_username: "@maintain_hive"
github_username:  yyyyy

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: css

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
